# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='listuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ListUser',
        ),
    ]
